/*
Paso 1: Identifica qué variables se necesitan para determinar si una persona puede subirse a la montaña rusa.

Paso 2: en VS Code, crea esas variables.

Paso 3: en el mismo archivo de VS Code, usa comentarios para explicar en qué se deben configurar las variables para que la persona pueda subirse. 
*/ 

//Tipos de datos o mejor dicho tipos de variables que pueden haber
    
    //Los tipos de datos Primitivos

        //1_ String = caracteres o numeros, pero deben estar entre comillas 
            var miVariableDeCaracteres = "texto dummie 12345";

        //2_ Number = solo numeros y no deben ir con comillas
            var miVariableDeNumeros = 3.14;

        //3_ boolean = la VARIABLE puede tener un solo 1 valor, true o false (VERDADERO O FALSO)
            var miBooleano = true;

        //4_ undefined = significa que la variable no tiene valor
            var miUndefined;
            
        //5_ null  = es lo mismo que undefined pero la diferencia es que este tipo de dato lo coloca el programador                
            var miVariableSinValor = null ;


//tipo NUMBER
let Edad;

//tipo NUMBER
let altura;

/* 

Necesitamos tipos de datos NUMBER por que estaremos trabajando con numeros

*/
